version: 2
build:
  os: 'ubuntu-24.04'
  tools:
    nodejs: '20'
  jobs:
    install:
      - npm ci
    build:
      html:
        - npm run build
        - mkdir --parents $READTHEDOCS_OUTPUT/html/
        - cp --recursive build/* $READTHEDOCS_OUTPUT/html/
